// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVI3ZkAnZfPXV4FkkhIy1wyowDqVmp_io',
    appId: '1:48481917454:web:937a79146fe9d63e18fa5f',
    messagingSenderId: '48481917454',
    projectId: 'cpr-project-aa05d',
    authDomain: 'cpr-project-aa05d.firebaseapp.com',
    storageBucket: 'cpr-project-aa05d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl3lNJBLB-f8RiupteToJXdpyEcK8AOMc',
    appId: '1:48481917454:android:827cb17c3e58542018fa5f',
    messagingSenderId: '48481917454',
    projectId: 'cpr-project-aa05d',
    storageBucket: 'cpr-project-aa05d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYkkbJx6TfD9bJgJiRmuoBH_H-p2--YLI',
    appId: '1:48481917454:ios:a48f3a31a9c684a518fa5f',
    messagingSenderId: '48481917454',
    projectId: 'cpr-project-aa05d',
    storageBucket: 'cpr-project-aa05d.firebasestorage.app',
    iosBundleId: 'com.example.careerPathRecommendation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYkkbJx6TfD9bJgJiRmuoBH_H-p2--YLI',
    appId: '1:48481917454:ios:a48f3a31a9c684a518fa5f',
    messagingSenderId: '48481917454',
    projectId: 'cpr-project-aa05d',
    storageBucket: 'cpr-project-aa05d.firebasestorage.app',
    iosBundleId: 'com.example.careerPathRecommendation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVI3ZkAnZfPXV4FkkhIy1wyowDqVmp_io',
    appId: '1:48481917454:web:72a401355b23a97618fa5f',
    messagingSenderId: '48481917454',
    projectId: 'cpr-project-aa05d',
    authDomain: 'cpr-project-aa05d.firebaseapp.com',
    storageBucket: 'cpr-project-aa05d.firebasestorage.app',
  );
}
